<?xml version="1.0"?>
<package format="2">
  <name>esvo2_core</name>
  <version>0.0.0</version>
  <description>The esvo2_core package.</description>

  <!-- One maintainer tag required, multiple allowed, one person per tag -->
  <!-- Example:  -->
  <maintainer email="eeyzhou@ust.hk">Yi Zhou</maintainer>

  <!-- One license tag required, multiple allowed, one license per tag -->
  <!-- Commonly used license strings: -->
  <!--   BSD, MIT, Boost Software License, GPLv2, GPLv3, LGPLv2.1, LGPLv3 -->
  <license>GPLv3</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  
  <depend>cv_bridge</depend>
  <depend>event_camera_codecs</depend>
  <depend>event_camera_msgs</depend>
  <depend>events_repackaging_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>image_transport</depend>
  <depend>libceres-dev</depend>
  <depend>libunwind-dev</depend> <!-- glog dependency that is not installed!-->
  <depend>minkindr</depend>
  <depend>minkindr_conversions</depend>
  <depend>opencv</depend>
  <depend>pcl_ros</depend>
  <depend>rclcpp</depend>
  <depend>tf2</depend>
  <depend>tf2_geometry_msgs</depend>
  <!-- The export tag contains other, unspecified, tags -->
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
